### ISSUE TITLE
NoMethodError: undefined method `task' for Sinatra::Application:Class

### ISSUE THREAD

**Issue by williamhqs** [janko-m/sinatra-activerecord#46]
Hi i am new to Sinatra, i want to create&connect mysql database by:
```    
 rake db:create RACK_ENV=production
```
How should i use this ? Thanks!

What's this mean? **.app** is which include `class Api < Sinatra::Base` file, and if l load **.app** file, i load databas.yml automaticly?
```
namespace :db do
  task :load_config do
    require "./app"
  end
end
```
After i add **require "sinatra/activerecord/rake"'**to my Rakefile, 
**Rakefile**
```
require "sinatra/activerecord/rake"
```
I have a database.yml under config folder. Does this file should load automatic right?

--------------------**update**---------------------------
I load my `application.rb` in rake file.The error now is:
```
rake aborted!
NoMethodError: undefined method `task' for Sinatra::Application:Class
```
-----------------------------------------------------------------------
**database.yml'**
```
development:
  database: fsdev
  encoding: utf8
  adapter: mysql2
  username: root
  password: '123123'
  pool: 5
  timeout: 5000
  host: 127.0.0.1
test:
  database: fsdev
  encoding: utf8
  adapter: mysql2
  username: root
  password: '123123'
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  database: fsproduction
  encoding: utf8
  adapter: mysql2
  username: root
  password: '123123'
  host: 127.0.0.1
  pool: 5
  timeout: 5000

```
