### ISSUE TITLE
rake db:create not creating production dbase

### ISSUE THREAD

**Issue by SeanMeh** [janko-m/sinatra-activerecord#77]
When running `rake db:create`, it creates Development and Test databases but not Production regardless of the environment specified.

My Sinatra app's environment gets set correctly prior to loading the sinatra-activerecord gem, and `rake db:migrate` does try to use the production `database.yml` settings.  It just can't migrate because `rake db:create` isn't creating the database.

The output of `rake db:create` (regardless of any environment I specify) is:

```
fbweb_dev already exists
fbweb_test already exists
```

This is my database.yml file:

```
production:
  adapter: postgresql
  database: fbweb_prod
  pool: 5
  timeout: 5000
  username: postgres
  password: 
  host: localhost

development:
  adapter: postgresql
  database: fbweb_dev
  pool: 5
  timeout: 5000
  username: postgres
  password: 
  host: localhost

test:
  adapter: postgresql
  database: fbweb_test
  pool: 5
  timeout: 5000
  username: postgres
  password: 
  host: localhost
```
Here's the bit in my `app.rb` file which gets loaded when running `rake db:create`

```
require 'sinatra'
configure do
  set :environment, :production
end

require 'sinatra/activerecord'
```

I'm just testing this locally now.  Obviously I wouldn't have `development` and `test` settings in my production environment, and wouldn't post up my production `database.yml` file.  ;P
